# Generated by Django 5.1.7 on 2025-06-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='news_images')),
                ('type', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('all_edited_image', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_id', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='template_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
