# Generated by Django 5.1.7 on 2025-05-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='edited_image',
        ),
    ]
