# Generated by Django 5.2.3 on 2025-06-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
